### ISSUE TITLE
GitHub link connects to wrong repo

### ISSUE THREAD

**Issue by bendoesai** [swordgeo/mulligan-tracker#1]
GitHub link in the footer of site links to the MCHREC repo rather than mulligan-tracker.

![image](https://github.com/swordgeo/mulligan-tracker/assets/60076753/b2b46301-a384-4e1e-a0e5-c3fd7278c8cf)

**Comment by swordgeo** [comment]
Thanks! That has been fixed. Appreciate it, friend.
